// <auto-generated />
using BirazdanKapinda.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BirazdanKapinda.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240108205515_addImageUrlToProduct")]
    partial class addImageUrlToProduct
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BirazdanKapinda.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Elektrikli Ev Aletleri"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Konsol, Oyun ve Oyuncu Ekipmanları"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "Ev-Ofis ve Yaşam"
                        });
                });

            modelBuilder.Entity("BirazdanKapinda.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AoS")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ListPrice")
                        .HasColumnType("float");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductFeatures")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AoS = 19,
                            CategoryId = 1,
                            Description = "Daha hızlı ütüleme ve güçlü performans",
                            ImageUrl = "",
                            ListPrice = 2400.0,
                            ProductCode = "117a34",
                            ProductFeatures = "Güç (Watt) - 2401 Watt ve Üzeri, Otomatik Kapanma - Var, Kireç Önleme - Var , Garanti Tipi - Resmi Distribütör Garantili",
                            Title = "Buharlı Ütü Makinesi"
                        },
                        new
                        {
                            Id = 2,
                            AoS = 35,
                            CategoryId = 1,
                            Description = "Akülü Çift Titan Şanzuman Premıum Li-on Şarjlı Matkap Usta Set",
                            ImageUrl = "",
                            ListPrice = 800.0,
                            ProductCode = "222b07",
                            ProductFeatures = "Voltaj - 12 Volt Max Performans 128 Volt, Akü tipi - 2 Adet Li-Ion BATARYA Akü kapasitesi - 1.5 Ah Max, Şarj Dolum süresi - 1 saat, Tork mekanizması - Var",
                            Title = "Şarjlı Matkap Usta Set"
                        },
                        new
                        {
                            Id = 3,
                            AoS = 955,
                            CategoryId = 2,
                            Description = "Valta Led Ampul 220-240v 3000k E27 5w Sıcak Beyaz",
                            ImageUrl = "",
                            ListPrice = 24.0,
                            ProductCode = "172t01",
                            ProductFeatures = "Ampul Teknolojisi - Led Ampul, Dim Özelliği - Yok, Duy Tipi - E27, Güç (Watt) - 5 Watt",
                            Title = "Led Ampul"
                        },
                        new
                        {
                            Id = 4,
                            AoS = 50,
                            CategoryId = 2,
                            Description = "Çift Kişilik, Camel Renk, Pamuklu Yatak Örtüsü",
                            ImageUrl = "",
                            ListPrice = 1100.0,
                            ProductCode = "604n41",
                            ProductFeatures = "Materyal - Pamuklu , Renk - Kahverengi, Desen - Çizgi, Boyut/Ebat - 250x260",
                            Title = "Çift Kişilik Yatak Örtüsü"
                        },
                        new
                        {
                            Id = 5,
                            AoS = 350,
                            CategoryId = 2,
                            Description = "240 Fonksiyonlu Bilimsel Hesap Makinesi",
                            ImageUrl = "",
                            ListPrice = 240.0,
                            ProductCode = "252h00",
                            ProductFeatures = "10+2 Haneli, İki Satırlı Dayanıklı Ekran, Temel İstatistik ve Matematik İşlemleri, Kayarak Takılan Koruyucu Sert Kapak",
                            Title = "Hesap Makinesi"
                        },
                        new
                        {
                            Id = 6,
                            AoS = 350,
                            CategoryId = 3,
                            Description = "Bordo Renk 0.7 Uçlu Kalem",
                            ImageUrl = "",
                            ListPrice = 64.0,
                            ProductCode = "785f24",
                            ProductFeatures = "Renk - Bordo, Çevirince ortaya çıkan ekstra silgi, Kauçuk kılıf ile rahat ve ergonomik tutuş",
                            Title = "Uçlu Kalem"
                        });
                });

            modelBuilder.Entity("BirazdanKapinda.Models.Product", b =>
                {
                    b.HasOne("BirazdanKapinda.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
